[package]
name = "driver-aic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "De Apple Interrupt Controller (AIC2/AIC3, t8132) als cpu::irq::Controller."

[dependencies]
dev = { path = "../../dev" }
cpu = { path = "../../cpu" }

[lints]
workspace = true
