#!/bin/sh -e
# refork-netstack.sh — regenereert de fork-branches van lneto en go-net uit de
# hopos-branches, en vertelt wat er daarna nog met de hand moet.
#
# STATUS 12-08: hop-os gebruikt lneto/go-net NIET meer — de netstack is
# xinix00/lean/leannet (docs/leannet-ontwerp.md, lean/leannet/DESIGN.md). Dit
# script blijft staan voor de open PR's bij soypat/lneto en usbarmory/go-net
# (#178-#183, go-net#5/#6): die zijn een bijdrage, geen onderhoudsplicht. Voor
# HopOS zelf is hier niets meer nodig.
#
# WAAROM TWEE BRANCHES PER CLONE
#
#   hopos  het UPSTREAM module-pad (github.com/soypat/lneto,
#          github.com/usbarmory/go-net). Hier leven onze fixes en hiervandaan
#          maken we PR-branches: upstream kan een diff met een gewijzigd
#          module-pad niet gebruiken.
#   fork   hopos + één mechanische commit die het module-pad naar het onze zet
#          (github.com/xinix00/…). Hier taggen we, en hierop pinnen metal/go.mod.
#
# Waarom een fork-pad en geen `replace`: een replace geldt alleen in de main
# module. Alles wat metal importeert (hop-os-surf, de vitals/welcome-apps) zag
# een replace in metal/go.mod dus NIET en bouwde tegen ongepatchte upstream —
# stil, want het compileert prima. Met een fork-pad reist de netstack mee in de
# require-graaf.
#
# UPSTREAM OVERNEMEN, de hele lus:
#
#   1. cd ~/Git/lneto && git checkout hopos && git pull origin main   (of rebase)
#   2. tools/refork-netstack.sh                 # bouwt `fork` opnieuw + test
#   3. per clone: git tag -a vX.Y.Z-hopos.N -m "…" && git push fork vX.Y.Z-hopos.N
#   4. metal/go.mod: de twee versies bijwerken, dan tools/test.sh
#
# Stap 3 blijft handwerk: een versie kiezen is een beslissing (en de tag moet
# HOGER zijn dan élke upstream-tag, anders pakt `@latest` upstream-code met het
# verkeerde module-pad — meegemaakt: upstream stond al op v0.3.2 terwijl onze
# eerste poging v0.2.1-hopos.1 heette).

DIR="$(cd "$(dirname "$0")/.." && pwd)" # absoluut: refork() cd't naar de clones
LNETO="${LNETO_DIR:-$HOME/Git/lneto}"
GONET="${GONET_DIR:-$HOME/Git/go-net}"

refork() { # refork <dir> <sed-expressie> <naam>
	dir=$1; expr=$2; name=$3
	echo "== $name: fork-branch uit hopos ==" >&2
	cd "$dir"
	[ -z "$(git status --porcelain)" ] || { echo "$name: werkboom niet schoon" >&2; exit 1; }
	git rev-parse --verify -q hopos >/dev/null || { echo "$name: geen hopos-branch" >&2; exit 1; }

	# De oude fork weggooien en opnieuw maken: hij is per definitie afgeleid, dus
	# een merge-conflict oplossen zou onzin zijn. Wie er iets in commit dat niet
	# in hopos staat, verliest het hier — en dat is de bedoeling.
	git checkout -q hopos
	git branch -D fork -q 2>/dev/null || true
	git checkout -q -b fork
	# shellcheck disable=SC2086
	git grep -l -E 'github\.com/(soypat/lneto|usbarmory/go-net)' -- '*.go' '*go.mod' \
		| xargs sed -i '' $expr
	if [ -n "$(git status --porcelain)" ]; then
		git add -A
		git commit -q -m "fork: module path onder github.com/xinix00

Mechanisch gegenereerd door tools/refork-netstack.sh in de HopOS-repo; de
hopos-branch houdt het upstream-pad en blijft de basis voor pull requests."
	fi
	echo "$name: fork = $(git log --format=%h -1) (hopos = $(git log --format=%h -1 hopos))" >&2
}

refork "$LNETO" '-e s|github.com/soypat/lneto|github.com/xinix00/lneto|g' lneto
refork "$GONET" '-e s|github.com/soypat/lneto|github.com/xinix00/lneto|g -e s|github.com/usbarmory/go-net|github.com/xinix00/go-net|g' go-net

# go-net's go.mod vraagt meer dan een pad-omzetting: de hopos-branch heeft een
# pad-replace naar deze Mac (nodig zolang we daar rechtstreeks op werken), en de
# fork moet in plaats daarvan ONZE lneto-tag pinnen. Welke tag, zegt metal/go.mod
# — dat is de plek waar de versiekeuze hoort te liggen. Zonder deze stap draagt
# de fork een replace naar /Users/derek en bouwt hij nergens anders.
WANT=$(sed -n 's|.*github.com/xinix00/lneto \(v[^ ]*\).*|\1|p' "$DIR/metal/go.mod" | head -1)
[ -n "$WANT" ] || { echo "metal/go.mod noemt geen xinix00/lneto-versie" >&2; exit 1; }
cd "$GONET"
python3 - "$WANT" <<'PY'
import re, sys
wanted = sys.argv[1]
s = open('go.mod').read()
s = re.sub(r'^replace github\.com/xinix00/lneto => .*\n', '', s, flags=re.M)
s = re.sub(r'(github\.com/xinix00/lneto )v[^\s]+', r'\g<1>' + wanted, s)
open('go.mod', 'w').write(s)
PY
# tidy erna: die sorteert de require-blokken en schrijft de go.sum-hashes van
# onze lneto-tag. Zonder dat bouwt de fork alleen waar die hashes al bekend zijn.
GOFLAGS=-mod=mod go mod tidy 2>/dev/null || {
	echo "go-net: go mod tidy faalde — go.sum mogelijk incompleet" >&2; exit 1; }
if [ -n "$(git status --porcelain)" ]; then
	git add -A
	git commit -q -m "fork: pin lneto $WANT, drop the local path replace

Also generated by tools/refork-netstack.sh; the version comes from
metal/go.mod so there is one place that decides it."
	echo "go-net: lneto gepind op $WANT" >&2
fi

echo "== testen ==" >&2
(cd "$LNETO" && go test ./... >/dev/null && echo "lneto: suite groen" >&2)

cat >&2 <<EOF

Klaar. Nog met de hand:
  1. tag per clone (HOGER dan élke upstream-tag):
       cd $LNETO  && git push fork fork && git tag -a vX.Y.Z-hopos.N -m "…" && git push fork vX.Y.Z-hopos.N
       cd $GONET  && git push fork fork && git tag -a vX.Y.Z-hopos.N -m "…" && git push fork vX.Y.Z-hopos.N
  2. metal/go.mod: de twee versies bijwerken
  3. tools/test.sh
EOF
