[package]
name = "driver-virtionet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "virtio-net over virtio-mmio (QEMU virt) of virtio-pci (EDK2): de virtqueues, DMA-buffers, batching."

[dependencies]
dev = { path = "../../dev" }
driver-virtiopci = { path = "../virtiopci" }
sync = { path = "../../sync" }
netdev = { path = "../../netdev" }
bounded = { path = "../../bounded" }

[lints]
workspace = true
